aws_dbt_snowflake_project:
  outputs:
    dev:
      account: LYLRUMH-GZ18622
      database: AIRBNB
      password: Rishabhkapoor8765
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: RISHABHKAPOOR
      warehouse: COMPUTE_WH
  target: dev
